#!/bin/bash

## Description: Bootstrap the test application

composer install
# Reset database to ensure a clean state
vendor/bin/console doctrine:database:drop --force --if-exists
vendor/bin/console doctrine:database:create
# Run all migrations (Sylius + plugin)
vendor/bin/console doctrine:migration:migrate -n
# Install default fixtures
vendor/bin/console sylius:fixtures:load -n
# Build and install frontend dependencies
(cd vendor/sylius/test-application && yarn install)
(cd vendor/sylius/test-application && yarn run build:prod)
vendor/bin/console assets:install
